
services:
  code-challenge-migration:
    container_name: code-challenge-migration
    image: code-challenge-migration:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080/tcp
    restart: always